### ISSUE TITLE
Powershell PDF form fill issue

### ISSUE THREAD

**Issue by Babble-on** [adbertram/Random-PowerShell-Work#12]
Hello,

I found your powershell script that fills out PDF forms on TomsITPro and it was perfect for what i was trying to accomplish.  However I have run into an issue that i was hoping you might be able to assist with.  The script I am using it in is quite complicated so I will spare you the details.

I am having no issue loading the iTextSharp.dll or finding the correct fields with your expertly written function. The issue arises when i try to fill in the data of my PDF template with the data from a variable. For Example: 

Save-PdfField -Fields @{'W R' = '$Global:PDF_WR';
'Territory' = '$Global:PDF_Territory';
'Project Name' = '$Global:PDF_Project';
'Date' = '$Global:PDF_Date';
'Stock ID' = '$Global:PDF_STOCK';
'Stock ID-0' = '$Global:PDF_STOCK0';
'Stock ID-1' = '$Global:PDF_STOCK1';
} -InputPdfFilePath "$template" -ITextSharpLibrary "$U\itextsharp.dll" -OutputPdfFilePath 'C:\MISC Projects\test.pdf'

The PDF is being created but the fields are being filled in with the literal variable names and not the data contained within.  As you can see I have attempted to make changes to the scope of the variables as well as a few other tweaks to attempt to get this to work.  

I will continue to try new ideas as I go and will update you if i find a solution but i figured i would ask the master if you had any insight.   Any help would be greatly appreciated.

EDIT:

Also forgot to mention , I am running PSVersion 5 build 10240 revision 16384

**Comment by adbertram** [comment]
Remove the single quotes around the variable names. That should do it.

**Comment by Babble-on** [comment]
Thanks I actually just came back to update you that I figured this out.   

Thanks for your help and awesome script.

**Comment by aaroncalderon** [comment]
@Babble-on Care to share how you solved the issue? Will be deeply appreciated.

**Comment by Babble-on** [comment]
@aaroncalderon  Indeed it was.   Apologies in my excitement i forgot to give details
