### ISSUE TITLE
New-LogEntry.ps1 errors on empty value for $Label

### ISSUE THREAD

**Issue by backintheday41** [adbertram/Random-PowerShell-Work#13]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error stops script from running

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Occurs whenever the script is run.  I believe the problem to be the following: the variable $Label is not given a value during the split of $Value.  $Value is then given $Split[0], but $Label is not given $Split[1].  Therefore, $Label is empty when used in the subsequent If statement.

foreach ($Value in $Values) {
				$Split = $Value.Split(' ')
				$Value = $Split[0]
                          ## adding the following line for $Label allows the script to run successfully
                                $Label = $Split[1]  
				if ($AllowedLabels -notcontains $Label) {

**What is the expected behavior?**
The script is expected to behave normally, to append a line to a CSV file

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Not related to a particular version

**Comment by adbertram** [comment]
This should be fixed now.
