### ISSUE TITLE
Get-UserLogonSessionHistory wrong path for nested OUs and Unlocked time issue

### ISSUE THREAD

**Issue by david-binard** [adbertram/Random-PowerShell-Work#3]
Get-UserLogonSessionHistory is a great start for what I need, but there are a couple of issues.
I have nested OUs, and the path built in the $ou variable is wrong for me (reverse order).
The fix for that is to insert the following line above the $ou assignment (line 59):
<CODE>[array]::Reverse($oSplit)</CODE>

The other issue is that the Locked events all have the same time for a given session (the highest value of all the locked events).
So, instead of something like this, which is what we would want (I'm using Export-CSV):

"2/12/2016 4:45:00PM","Unlocked","2/12/2016 6:00:00PM","Logoff"
"2/12/2016 12:30:00PM","Unlocked","2/12/2016 4:30:00PM","Locked"
"2/12/2016 9:45:00AM","Unlocked","2/12/2016 12:00:00PM","Locked"
"2/12/2016 9:00:00AM","Logon","2/12/2016 9:30:00AM","Locked"

We get something like this:

"2/12/2016 4:45:00PM","Unlocked","2/12/2016 6:00:00PM","Logoff"
"2/12/2016 12:30:00PM","Unlocked","2/12/2016 4:30:00PM","Locked"
"2/12/2016 9:45:00AM","Unlocked","2/12/2016 4:30:00PM","Locked"
"2/12/2016 9:00:00AM","Logon","2/12/2016 4:30:00PM","Locked"

**Comment by david-binard** [comment]
My fix for line 59 didn't come through.
Here it is again nested in CODE tages:

<CODE>[array]::Reverse($oSplit)</CODE>

**Comment by adbertram** [comment]
Got it. Thanks. I'll update the OU. Would you mind issuing a pull request for the other problem? I don't really support these scripts but will gladly take a PR and merge it if you think they need to be improved.

**Comment by david-binard** [comment]
Sure, I'll do that once I come up with a working solution.
