### ISSUE TITLE
Get-WeekDay.ps1 return today's dates if asking for [nexs|last] today

### ISSUE THREAD

**Issue by aaroncalderon** [adbertram/Random-PowerShell-Work#4]
First of all, awesome scripts. 

I noticed that if you ask for [next|last] Monday and today is Monday, it returns today's date.

Is this the intended functionality?

**Comment by adbertram** [comment]
No. It is not. If you come up with a fix, submit a pull request and I'd be glad to merge it in.

- Adam

**Comment by aaroncalderon** [comment]
I do not have a 'fix' for it just now, however, the script actually works well with the current behavior on my script logic. 

@adbertram In your opinion, would it be better to provide a `[switch]` (flag) to change the behavior, or no flag, and just change the script.

Will you be interested on the changes I did regarding the `-fromDate` mentioned below?

Thanks. 

# Additional Info

I actually modified the script and added an optional parameter (`-fromDate`) to provide a date, so if this date is provided, it calculates the `[next|last] day` based on the provided date instead of today's date.

However, If I ask for `next monday` and my `-fromDate` is a Monday, I do want that date returned (which is the current behavior). I can just check before hand if `-fromDate` is a Monday off course.

**Comment by adbertram** [comment]
No flag. You can just change the script as necessary. That's what source control is all about! :)

**Comment by aaroncalderon** [comment]
Alright, I created the [Get-WeekdayFrom.ps1](https://github.com/aaroncalderon/Random-PowerShell-Work/blob/aaroncalderon-get-weekdayfrom/PowerShell%20Internals/Get-WeekdayFrom.ps1) if you are interested.

Thanks for your time and effort.
