### ISSUE TITLE
missing xml 

### ISSUE THREAD

**Issue by AliBawazeEer** [adbertram/Random-PowerShell-Work#6]
well , i can't see the xml file any more in github ..  may i know if this can work on remote windows 7 machine bearing in mind i will be having privilege account to set up credentials

**Comment by adbertram** [comment]
What script are you referring to?

**Comment by AliBawazeEer** [comment]
@adbertram 
i am referring to https://github.com/adbertram/Random-PowerShell-Work/blob/master/ActiveDirectory/Rejoin-Computer.ps1 
don't know what is missing .. let me try explain how my environment works 

got the password for local machine by default username is  administrator & password  ( variable ) 

for my helpdesk member we use N account privilege account to rejoin the domain ... using team viewer .. 


to make it efforteless i wonder if this can be implemented

**Comment by AliBawazeEer** [comment]
Note: the privilege account will always have a username & password 
for example  
abb54667n < username 
Password@123  < password 

above accounts can be used by analyst of helpdesk

**Comment by AliBawazeEer** [comment]
@adbertram my powershell scripts limited , ,, 

awaiting your response , thank you

**Comment by AliBawazeEer** [comment]
@adbertram  you are refereeing to an xml file which i really have no idea and am quite confused ..
