### ISSUE TITLE
Wait-Ping : A parameter cannot be found that matches parameter name 'Source'

### ISSUE THREAD

**Issue by harringg** [adbertram/Random-PowerShell-Work#7]
https://github.com/adbertram/Random-PowerShell-Work/blob/master/Networking/Wait-Ping.ps1

Issue arises with and without -verbose

Wait-Ping -ComputerName TestPC01 -Verbose

Wait-Ping : A parameter cannot be found that matches parameter name 'Source'.
At line:1 char:1
- Wait-Ping -ComputerName TestPC01  -Verbose
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Wait-Ping

System specs (Run Elevated)
Name             : Windows PowerShell ISE Host
Version          : 5.0.10586.51

**Comment by adbertram** [comment]
Thanks. I'll get this fixed.
